### ISSUE TITLE
Fails to install under python 3.5 due to copyright symbol in README.rst not being an ascii char

### ISSUE THREAD

**Issue by amishHammer** [paddycarey/dweepy#8]
===>  Configuring for py35-dweepy-0.2.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 14, in <module>
    long_description=open('README.rst').read(),
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8404: ordinal not in range(128)
**\* Error code 1

**Comment by urnenfeld** [comment]
I can confirm the issue,
I have got the following log from the [yocto recipe](https://github.com/urnenfeld/meta-widde/blob/master/recipes-devtools/python/python3-dweepy_0.2.0.bb): 

> DEBUG: Executing shell function do_compile
> Traceback (most recent call last):
>   File "setup.py", line 14, in <module>
>     long_description=open('README.rst').read(),
>   File "/media/oliver/Data80/raspberrypi/build-raspberrypi/tmp/sysroots/x86_64-linux/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
>     return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8404: ordinal not in range(128)
> ERROR: python3 setup.py build_ext execution failed.
> ERROR: Function failed: do_compile (log file is located at /media/oliver/Data80/raspberrypi/build-raspberrypi/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/python3-dweepy/0.2.0-r0/temp/log.do_compile.3426)

**Comment by jumpkick** [comment]
This type of thing (that already has trivial fix begging for a pull request, but isn't yet released) is so frustrating... I'm probably going to have to waste an hour figuring out how to repackage this thing because of a "(c)" character... argh...

**Comment by paddycarey** [comment]
dweepy 0.3.0 has been released on PyPI
